name: password_manager
description: A new Flutter project.
publish_to: 'none'

version: 3.7.0+33

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^8.0.3
  # Navigation
  go_router: ^16.0.0

  # BLoC
  flutter_bloc: ^9.1.1
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0

  # Secure Storage
  ## APP cache storage
  flutter_secure_storage: ^9.2.4
  # Local Authentication
  ## Fingerprint authentication
  local_auth: ^2.3.0

  # File Picker
  ## Store and read backup file
  file_picker: ^10.2.0

  # Internationalization
  intl: ^0.20.2

  # Encrypt
  ## Encrypt/Decrypt Passwords
  encrypt: ^5.0.3

  # Url Launcher
  ## Open URL links
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.6.0
  very_good_analysis: ^9.0.0

  analyzer: ^7.7.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana.ttf
