name: password_manager
description: A new Flutter project.
publish_to: 'none'

version: 3.3.3+22

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^8.0.1
  # Navigation
  go_router: ^14.3.0

  # BLoC
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

  # Secure Storage
  ## APP cache storage
  flutter_secure_storage: ^9.2.2
  # Local Authentication
  ## Fingerprint authentication
  local_auth: ^2.3.0

  # File Picker
  ## Store and read backup file
  file_picker: ^8.1.3

  # Encrypt
  ## Encrypt/Decrypt Passwords
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6

  analyzer: ^5.13.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana.ttf
